# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    # You can also specify other tool versions:
    nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"
  jobs:
    post_install:
      - npm install -g jsdoc
# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

#Optionally build your docs in additional formats such as PDF and ePub
formats:
   - pdf
   - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   install:
   - requirements: docs/requirements.txt

# pure /* JavaScript */ docu 
# JSdoc readme: https://github.com/jsdoc/jsdoc autogenerate JS doc
# win MUST Set-ExecutionPolicy -ExecutionPolicy RemoteSigned in PowerShell (Admin)
# JSdoc: npm install -g jsdoc 
# ./node_modules/.bin/jsdoc ./static/js ;autocreates a HTML docu in /out folder

# integrate /* JavaScript */ in Python docu (Fullstack)
# https://pypi.org/project/sphinx-js/)
# pip install sphinx-js
# in /docs/conf.py add: 
# extensions = ['sphinx_js']
# js_source_path = '../../static/js'
# in a module.rst
# .. js:autofunction:: someFunction  - manual action for each fun or classes